# Generated by Django 5.2.1 on 2025-05-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reminder",
            old_name="remind_via",
            new_name="reminder_type",
        ),
    ]
